import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import { getSession } from 'next-auth/react'
import Login from '../components/Login'

export async function getServerSideProps(context) {
  //get user
  const session = await getSession(context);

  return {
    props: {
      session
    }
  }
}

export default function Home(props) {

  const { session } = props;
  if(!session) return <Login />

  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      <main>
        {/* Sidebar */}
        {/* Feed */}
        {/* Widgets */}
      </main>
    </div>
  )
}
