import Head from 'next/head';
import Header from '../components/Header';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { useSession } from 'next-auth/react';

export default function Home() {

  const { data: session, status } = useSession()

  if(!session) return <Login />;

  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header fbuser={session}/>

      <main className='flex'>

        {/* Sidebar */}

        <Sidebar fbuser={session} />

        {/* Feed */}

        <Feed fbuser={session}/>

        {/* Widgets */}

        <Widgets />

      </main>
    </div>
  )
}
